import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { completable } from "@modelcontextprotocol/sdk/server/completable.js";
import { z } from "zod";
import { suggestStoreNames } from "../shared/storeAutocomplete.js";
import { URIS } from "../uris.js";

/**
 * Prompt: nanostores/debug-store
 * Debug a specific store with both static and runtime analysis
 */
export function registerDebugStorePrompt(server: McpServer): void {
	server.registerPrompt(
		"debug-store",
		{
			title: "Debug a Nanostores store",
			description:
				"Analyze a Nanostores store by combining static code analysis (AST graph) with runtime behavior (@nanostores/logger events). Find anti-patterns, performance issues, and suggest refactoring.",
			argsSchema: {
				store_name: completable(
					z
						.string()
						.describe(
							"Name of the store to debug (for example `$counter`). Autocomplete is based on the scanned Nanostores graph.",
						),
					async value => {
						return suggestStoreNames(value);
					},
				),
			},
		},
		({ store_name }) => {
			const runtimeProfileUri = URIS.runtimeStoreTemplate.replace("{key}", store_name);

			const text = [
				"<ROLE>",
				`You are a senior frontend engineer and Nanostores maintainer.`,
				`You are helping debug a specific Nanostores store named "${store_name}" in this codebase.`,
				"Your goal is to combine static structure (AST graph) with runtime behavior (logger events)",
				"to identify issues and propose practical improvements.",
				"Write in clear, professional, but friendly language.",
				"</ROLE>",
				"",
				"<ENVIRONMENT>",
				"You are running inside an MCP client.",
				"For this task, you have access to the following MCP resources and tools provided by this server:",
				"",
				"Primary combined profile (recommended):",
				`- ${runtimeProfileUri} — runtime store profile with BOTH static data (file, kind, relations, subscribers)`,
				"  and runtime data (stats, recentEvents, activity metrics) merged together when available.",
				"",
				"Additional static and global runtime context (optional, if needed):",
				`- ${URIS.storeById(store_name)} — pure static analysis for this store (AST graph, subscribers, relations).`,
				`- ${URIS.graph} — project-wide Nanostores dependency graph (files, stores, relations).`,
				`- ${URIS.runtimeStats} — aggregated runtime statistics across all stores.`,
				"",
				"Useful tools:",
				"- `nanostores_store_activity` — detailed activity timeline for specific stores.",
				"- `nanostores_find_noisy_stores` — compare this store against other high-activity stores.",
				"",
				"Treat these resources and tools as your ONLY reliable sources of truth about this store's behavior",
				"in the current project. Do NOT assume other hidden instrumentation exists.",
				"</ENVIRONMENT>",
				"",
				"<RETRIEVAL_INSTRUCTIONS>",
				"Before you start writing the final debug report, you MUST:",
				"",
				`1. Attempt to call the runtime store profile resource "${runtimeProfileUri}" and read its JSON representation (mimeType "application/json").`,
				"   - If this runtime profile does not exist or has no runtime data, explicitly note that runtime information is missing or limited.",
				"2. If the runtime profile is available, use it as your primary source of truth for this store.",
				"",
				"3. When you need more detail about static structure, optionally use:",
				`   - ${URIS.storeById(store_name)} — for store definition, relations, and subscribers.`,
				`   - ${URIS.graph} — for broader project context and how this store fits into the overall graph.`,
				"",
				"4. When you need global runtime context or comparisons:",
				`   - Use ${URIS.runtimeStats} and the tools "nanostores_find_noisy_stores" and "nanostores_store_activity".`,
				"",
				"5. When you want to back up recommendations with official guidance:",
				"   - Use `nanostores_docs_for_store` to retrieve docs for this store kind.",
				"   - Use `nanostores_docs_search` to find best practices for patterns or problems you detect.",
				"",
				"Do NOT invent metrics, events, or relationships that are not present in these resources.",
				"If some information you would normally want is missing, explicitly mention that limitation instead of guessing.",
				"</RETRIEVAL_INSTRUCTIONS>",
				"",
				"<ANALYSIS_STEPS>",
				"After loading the runtime store profile (and any additional resources), but BEFORE writing the final answer,",
				"mentally perform the following structured analysis:",
				"",
				"1. Store health check:",
				"- Determine whether the store is mounted/used at all (mount events, subscribers).",
				"- Inspect change frequency: is it very low (possibly dead/unused) or unusually high (potential performance issue)?",
				"- Check for errors or failed actions related to this store, if such data is available.",
				"",
				"2. Anti-pattern detection:",
				"- Too chatty: frequent updates in a short time window (for example, sustained > ~10 changes/second).",
				"- Large payload: storing large or deeply nested objects where a more normalized structure may be better.",
				"- Over-subscribed: many subscribers/components depending on this store, making changes very expensive.",
				"- Under-utilized: defined but rarely or never mounted/used (potential dead code).",
				"- Action chaos: many different actions or modules mutating this store without clear ownership.",
				"",
				"3. Performance considerations:",
				"- Whether the current store structure is likely to trigger unnecessary re-renders or recomputations.",
				"- Whether derived/computed stores could reduce redundant calculations or heavy updates.",
				"- Whether the store should be split into multiple smaller stores with clearer responsibilities.",
				"",
				"4. Architectural recommendations:",
				"- How this store fits into the project architecture (core shared state vs local feature state).",
				"- Whether the responsibilities of this store are too broad or unclear.",
				"- Which refactorings would make its role more explicit and maintainable.",
				"",
				"5. Documentation and best practices:",
				"- Use Nanostores docs tools to confirm whether detected patterns align with recommended usage.",
				"- Look for documented best practices for performance, normalization, and derived stores.",
				"",
				"Use this analysis to drive your explanation, but do NOT output raw JSON dumps.",
				"</ANALYSIS_STEPS>",
				"",
				"<TASK>",
				"Using ONLY the information from the runtime store profile, supporting static resources, runtime statistics,",
				"and Nanostores documentation tools, produce a focused debug report for this store.",
				"",
				"Your report MUST cover:",
				"- A clear overall verdict on the store's health (for example: healthy / needs attention / critical).",
				"- Key observed metrics (for example: mount count, number of changes, error counts, notable spikes).",
				"- Specific issues or risks you found, each with a short explanation and severity.",
				"- Concrete, actionable recommendations to improve correctness, performance, and architecture.",
				"- Optional references to relevant official Nanostores documentation to support your suggestions.",
				"",
				"Assume the reader already knows basic Nanostores concepts; focus on this store and this project.",
				"</TASK>",
				"",
				"<OUTPUT_FORMAT>",
				"Return a Markdown document with the following structure:",
				"",
				"1. **Summary**",
				"   - One-line verdict on the store's health (for example: `healthy`, `needs attention`, `critical`).",
				"",
				"2. **Key Metrics**",
				"   - List the most important metrics you observed (mounts, changes, actions, errors, etc.).",
				"",
				"3. **Issues Found**",
				"   - A bullet list of concrete problems or risks.",
				"   - For each issue, include a short description and an approximate severity (low/medium/high).",
				"",
				"4. **Recommendations**",
				"   - Concrete, actionable refactoring and optimization steps.",
				"   - Prefer small, incremental changes over vague large rewrites.",
				"   - Include short code examples or pseudo-code where it clarifies the idea.",
				"",
				"5. **Documentation References**",
				"   - Mention which Nanostores docs or patterns support your recommendations",
				"     (for example: results from `nanostores_docs_for_store` / `nanostores_docs_search`).",
				"",
				"Guidelines:",
				"- Keep the report tightly focused on this store.",
				"- Use headings and bullet points to keep it readable.",
				"- Refer to files as `path/to/file.ts` and stores as `$storeName`.",
				"- Do NOT paste raw JSON from resources; always summarize and interpret.",
				"</OUTPUT_FORMAT>",
				"",
				"<QUALITY_GUIDELINES>",
				"- Base all concrete statements on data from the runtime profile, static graph, runtime statistics, and docs tools.",
				"- It is better to say “no runtime data is available for this store” than to guess its behavior.",
				"- If the store cannot be found in the static graph, clearly state that and suggest checking the name.",
				"- If there is no runtime data, still provide a static-structure-based analysis and explicitly call out that limitation.",
				"- Aim for high signal: prioritize the most important issues and recommendations.",
				"</QUALITY_GUIDELINES>",
			].join("\n");

			return {
				messages: [
					{
						role: "user",
						content: {
							type: "text",
							text,
						},
					},
				],
			};
		},
	);
}

/**
 * Prompt: nanostores/debug-project-activity
 * Overall runtime health analysis for the entire project
 */
export function registerDebugProjectActivityPrompt(server: McpServer): void {
	server.registerPrompt(
		"debug-project-activity",
		{
			title: "Debug project-wide Nanostores activity",
			description:
				"Analyze runtime behavior across all Nanostores in the project to find hot spots, error patterns, unused stores, and optimization opportunities.",
			argsSchema: {},
		},
		() => {
			const text = [
				"<ROLE>",
				"You are a senior frontend engineer and Nanostores maintainer.",
				"You are performing a comprehensive project-wide runtime analysis of all Nanostores stores in this codebase.",
				"Your goal is to identify hot spots, error patterns, dead or unused stores, and opportunities for architectural and performance improvements.",
				"Write in clear, professional, but friendly language.",
				"</ROLE>",
				"",
				"<ENVIRONMENT>",
				"You are running inside an MCP client.",
				"For this task, you have access to the following MCP resources and tools provided by this server:",
				"",
				"Runtime data:",
				`- ${URIS.runtimeStats} — aggregated runtime statistics for all stores.`,
				`- ${URIS.runtimeEvents} — recent runtime events across all stores.`,
				"",
				"Static structure:",
				`- ${URIS.graph} — project-wide Nanostores dependency graph (files, stores, relations).`,
				"",
				"Tools:",
				"- `nanostores_runtime_overview` — overall health report and summary.",
				'- `nanostores_find_noisy_stores` — identify high-activity or "chatty" stores.',
				"- `nanostores_store_activity` — deep dive into specific stores when needed.",
				"",
				"Treat these resources and tools as your ONLY reliable sources of truth about runtime behavior",
				"and store structure in this project.",
				"</ENVIRONMENT>",
				"",
				"<RETRIEVAL_INSTRUCTIONS>",
				"Before you start writing the final project-wide report, you SHOULD:",
				"",
				"- Use `nanostores_runtime_overview` to obtain a high-level summary of runtime health and key metrics.",
				"- Inspect aggregated statistics via:",
				`  - ${URIS.runtimeStats} for store-level metrics (activity, errors, mounts, etc.).`,
				"- Review recent events via:",
				`  - ${URIS.runtimeEvents} to spot patterns (bursts of activity, repeated errors, etc.).`,
				"- Use the project-wide graph:",
				`  - ${URIS.graph} to understand how hot or problematic stores fit into the overall architecture.`,
				"- When you need more detail on specific stores, use:",
				"  - `nanostores_find_noisy_stores` to identify candidates.",
				"  - `nanostores_store_activity` to inspect individual stores more deeply.",
				"",
				"Do NOT invent stores, metrics, or relationships that are not present in these resources.",
				"If some information you would normally want is missing, explicitly mention that limitation instead of guessing.",
				"</RETRIEVAL_INSTRUCTIONS>",
				"",
				"<ANALYSIS_STEPS>",
				"After collecting the necessary data, but BEFORE writing the final report, mentally perform the following analysis:",
				"",
				"1. Identify hotspots:",
				"- Which stores have the highest change frequency or activity metrics?",
				'- Are there "chatty" stores with frequent updates that may cause performance issues?',
				"- Which stores are most central in the dependency graph (many subscribers or relations)?",
				"",
				"2. Error analysis:",
				"- Which stores are associated with failing actions or errors in the runtime events?",
				"- Are there recurring error patterns or likely shared root causes?",
				"- What is the overall error rate relative to total actions/operations?",
				"",
				"3. Dead code and under-utilized stores:",
				"- Which stores appear to be never mounted or rarely used based on runtime data?",
				"- Are there stores that exist in the graph but show no meaningful runtime activity?",
				"- Identify likely candidates for cleanup or removal.",
				"",
				"4. Architectural insights:",
				"- Look at store dependency patterns: are a few stores centralizing too much responsibility,",
				"  or is state well-distributed across feature-level stores?",
				"- Are computed/derived stores used effectively to encapsulate logic, or do multiple consumers",
				"  recompute the same things?",
				"- Is there a clear separation between global core state and local feature state?",
				"",
				"5. Performance optimization opportunities:",
				"- Which stores are likely to have the biggest impact if optimized (high activity + many subscribers)?",
				"- Where could normalization or splitting stores reduce update costs?",
				"- Are there opportunities for memoization/caching or using computed stores to reduce redundant work?",
				"",
				"6. Documentation and best practices:",
				"- When in doubt about recommended patterns, use `nanostores_docs_search` to find relevant guidance.",
				"",
				"Use this structured analysis to guide your report, but do NOT dump raw data.",
				"</ANALYSIS_STEPS>",
				"",
				"<TASK>",
				"Using ONLY the information from runtime statistics, runtime events, the static graph, and the provided tools,",
				"produce a project-wide runtime health report for all Nanostores in this project.",
				"",
				"Your report MUST cover:",
				"- A high-level assessment of overall runtime health.",
				"- Counts and basic breakdowns (for example: total stores, active stores, problematic stores).",
				"- The most important hotspots and issues, prioritized by likely impact.",
				"- Concrete, prioritized recommendations for improving performance, reliability, and maintainability.",
				"- Optional references to relevant Nanostores documentation for key recommendations.",
				"</TASK>",
				"",
				"<OUTPUT_FORMAT>",
				"Return a Markdown document with the following structure:",
				"",
				"1. **Executive Summary**",
				"   - Overall health score or qualitative verdict.",
				"   - Number of stores (total, active, problematic).",
				"   - 3–5 key findings in bullet points.",
				"",
				"2. **Priority Issues**",
				"   - List the most critical problems first.",
				'   - For each issue, include affected stores and the expected impact (for example: "high render cost on product listing").',
				"",
				"3. **Detailed Analysis**",
				"   - Hot spots with relevant metrics (activity, errors, subscribers, etc.).",
				"   - Error patterns and likely shared causes.",
				"   - Dead or under-utilized stores as cleanup candidates.",
				"",
				"4. **Optimization Roadmap**",
				"   - A prioritized list of optimization and refactoring steps (high → low impact).",
				"   - For each step, briefly describe expected benefits and rough implementation effort (low/medium/high).",
				"   - Back key recommendations with references to Nanostores best practices, using `nanostores_docs_search` when helpful.",
				"",
				"Guidelines:",
				"- Focus on actionable insights rather than raw numbers.",
				"- Include specific store names and relevant metrics when they clarify the problem.",
				"- Provide short code-level examples or patterns only where they add clear value.",
				"</OUTPUT_FORMAT>",
				"",
				"<QUALITY_GUIDELINES>",
				"- Base all concrete statements on data from runtime and static MCP resources and tools.",
				"- It is better to say “the available runtime data is limited” than to over-generalize.",
				"- Prioritize issues and recommendations that are likely to have the biggest real-world impact.",
				"- Keep the report focused and readable for a team that will act on it.",
				"</QUALITY_GUIDELINES>",
			].join("\n");

			return {
				messages: [
					{
						role: "user",
						content: {
							type: "text",
							text,
						},
					},
				],
			};
		},
	);
}
